#!/usr/bin/env python
#Boa:App:BoaApp

import wx

import frm_data_rtsm

modules ={u'frm_data_rtsm': [1, 'Main frame of Application', u'frm_data_rtsm.py']}

class BoaApp(wx.App):
    def OnInit(self):
        self.main = frm_data_rtsm.create(None)
        self.main.Show()
        self.SetTopWindow(self.main)
        return True

def main():
    application = BoaApp(0)
    application.MainLoop()

if __name__ == '__main__':
    main()
